### PR TITLE
Hardens RecommendationRow._get against null values (closes #181).

### LINKED ISSUE #181: Sometimes get the wrong results when I backspace
This isn't 100% reproducible, but I tried it on a brand new profile (see recording below) and got it on the second try.

STR:
1) Type 'fac' to get facebook to prefill
2) Backspace over everything and type 'h'
3) See Facebook recommended

out-12

(edit: lol @ gif quality.  What are you kids using for web animations these days? webm?)

### PR DESCRIPTION
**Pull request by chuckharmston**
And a few drive-by semicolons.

r? @6a68

### CODE REVIEW

File: lib/ui/recommendation-row.js [hunk 1]
```diff
@@ -256,8 +256,10 @@ RecommendationRow.prototype = {
     const val = key.split('.').reduce(function(o, x) {
       return (typeof o == 'undefined' || o === null) ? o : o[x];
     }, this._data);
-    const isEmptyObject = (typeof val == 'object' && !Object.keys(val).length);
-    return (typeof val == 'undefined' || !val || isEmptyObject) ? null : val;
+    let isEmptyObject = val => {
+      return val && typeof val == 'object' && !Object.keys(val).length;
+    };
+    return (typeof val == 'undefined' || !val || isEmptyObject(val)) ? null : val;
```
Comment (jaredhirsch) [inline lib/ui/recommendation-row.js:262]: The `typeof val !== 'undefined'` check is only needed if the variable `val` might be uninitialized, but since it's defined as a const above, you don't need it.

I think you can get away with just doing this:

``` js
return !!val && !isEmptyObject(val) && val || null;
```

File: lib/ui/recommendation-row.js [hunk 2]
```diff
@@ -256,8 +256,10 @@ RecommendationRow.prototype = {
     const val = key.split('.').reduce(function(o, x) {
       return (typeof o == 'undefined' || o === null) ? o : o[x];
     }, this._data);
-    const isEmptyObject = (typeof val == 'object' && !Object.keys(val).length);
-    return (typeof val == 'undefined' || !val || isEmptyObject) ? null : val;
+    let isEmptyObject = val => {
+      return val && typeof val == 'object' && !Object.keys(val).length;
```
Comment (jaredhirsch) [inline lib/ui/recommendation-row.js:260]: you can skip the truthy check here, since you do it on line 262 before this function is called: `return typeof val == 'object' && !Object.keys(val).length`

File: lib/ui/recommendation-row.js [hunk 3]
```diff
@@ -256,8 +256,10 @@ RecommendationRow.prototype = {
     const val = key.split('.').reduce(function(o, x) {
       return (typeof o == 'undefined' || o === null) ? o : o[x];
     }, this._data);
```
Comment (jaredhirsch) [inline lib/ui/recommendation-row.js:258]: Optional suggestion: how about this alternative for the first part? It handles all possible edge cases (like trying to access object properties on an array). It's slower (using try-catch sends you into interpreted vs compiled mode), but we're calling this in the midst of dealing with the DOM anyway, so speed's not a primary concern.

``` js
const val = key.split('.').reduce((o,x) => {
  let result;
  try {
    result = o[x];
  } catch (ex) {}
  return result;
}, this._data);
```

In the spirit of minimizing changes just before launch, I'm fine with ignoring this suggestion, but wanted to put it out there.

**Comment by jaredhirsch** [comment]
@chuckharmston You know, it probably makes sense for us to rely on utils like lodash, rather than rolling our own without the benefit of unit tests. I've been resisting this idea out of laziness, but it makes more sense for us to spend an hour building a feature, rather than rewriting open source utils. There are definitely other spots in this addon that could benefit from replacement with open source tools.

Maybe I'll file a bug to replace this with lodash _.get after public launch, thoughts?

**Comment by jaredhirsch** [comment]
@chuckharmston R+ from me once comments are addressed

File: lib/ui/recommendation-row.js (hunk 2 above)
Comment (chuckharmston) [inline lib/ui/recommendation-row.js:260]: I originally thought so too, but somehow `val` was `null` in #181. This is the only substantial change in PR; I just restructured to a quick function to make it cleaner.

Comment (jaredhirsch) [inline lib/ui/recommendation-row.js:260]: Ah. If you look at the old line 259, you were doing the Object.keys(val) call without checking that val was truthy. `typeof null` is object, so that check didn't guard against null values.

Comment (chuckharmston) [inline lib/ui/recommendation-row.js:260]: Right. That covers the two substantive comments here, so I'm going to merge this. Followed up with https://github.com/mozilla/universal-search/issues/199, which we should do very shortly after launch.
